module.exports = {
    BasicControlCapabilityRouter: require("./BasicControlCapabilityRouter"),
    CarpetModeControlCapabilityRouter: require("./CarpetModeControlCapabilityRouter"),
    CombinedVirtualRestrictionsCapabilityRouter: require("./CombinedVirtualRestrictionsCapabilityRouter"),
    ConsumableMonitoringCapabilityRouter: require("./ConsumableMonitoringCapabilityRouter"),
    DebugCapabilityRouter: require("./DebugCapabilityRouter"),
    DoNotDisturbCapabilityRouter: require("./DoNotDisturbCapabilityRouter"),
    GoToLocationCapabilityRouter: require("./GoToLocationCapabilityRouter"),
    LEDControlCapabilityRouter: require("./LEDControlCapabilityRouter"),
    LocateCapabilityRouter: require("./LocateCapabilityRouter"),
    ManualControlCapabilityRouter: require("./ManualControlCapabilityRouter"),
    MapResetCapabilityRouter: require("./MapResetCapabilityRouter"),
    MapSegmentEditCapabilityRouter: require("./MapSegmentEditCapabilityRouter"),
    MapSegmentRenameCapabilityRouter: require("./MapSegmentRenameCapabilityRouter"),
    MapSegmentationCapabilityRouter: require("./MapSegmentationCapabilityRouter"),
    MapSnapshotCapabilityRouter: require("./MapSnapshotCapabilityRouter"),
    MappingPassCapabilityRouter: require("./MappingPassCapabilityRouter"),
    PendingMapChangeHandlingCapabilityRouter: require("./PendingMapChangeHandlingCapabilityRouter"),
    PersistentMapControlCapabilityRouter: require("./PersistentMapControlCapabilityRouter"),
    PresetSelectionCapabilityRouter: require("./PresetSelectionCapabilityRouter"),
    SensorCalibrationCapabilityRouter: require("./SensorCalibrationCapabilityRouter"),
    SpeakerTestCapabilityRouter: require("./SpeakerTestCapabilityRouter"),
    SpeakerVolumeControlCapabilityRouter: require("./SpeakerVolumeControlCapabilityRouter"),
    VoicePackManagementCapabilityRouter: require("./VoicePackManagementCapabilityRouter"),
    WifiConfigurationCapabilityRouter: require("./WifiConfigurationCapabilityRouter"),
    ZoneCleaningCapabilityRouter: require("./ZoneCleaningCapabilityRouter")
};
