module.exports = {
    AutoEmptyDockAutoEmptyIntervalControlCapabilityRouter: require("./AutoEmptyDockAutoEmptyIntervalControlCapabilityRouter"),
    AutoEmptyDockManualTriggerCapabilityRouter: require("./AutoEmptyDockManualTriggerCapabilityRouter"),
    BasicControlCapabilityRouter: require("./BasicControlCapabilityRouter"),
    CarpetSensorModeControlCapabilityRouter: require("./CarpetSensorModeControlCapabilityRouter"),
    CombinedVirtualRestrictionsCapabilityRouter: require("./CombinedVirtualRestrictionsCapabilityRouter"),
    ConsumableMonitoringCapabilityRouter: require("./ConsumableMonitoringCapabilityRouter"),
    DoNotDisturbCapabilityRouter: require("./DoNotDisturbCapabilityRouter"),
    GoToLocationCapabilityRouter: require("./GoToLocationCapabilityRouter"),
    HighResolutionManualControlCapabilityRouter: require("./HighResolutionManualControlCapabilityRouter"),
    LocateCapabilityRouter: require("./LocateCapabilityRouter"),
    ManualControlCapabilityRouter: require("./ManualControlCapabilityRouter"),
    MapResetCapabilityRouter: require("./MapResetCapabilityRouter"),
    MapSegmentEditCapabilityRouter: require("./MapSegmentEditCapabilityRouter"),
    MapSegmentRenameCapabilityRouter: require("./MapSegmentRenameCapabilityRouter"),
    MapSegmentationCapabilityRouter: require("./MapSegmentationCapabilityRouter"),
    MapSnapshotCapabilityRouter: require("./MapSnapshotCapabilityRouter"),
    MappingPassCapabilityRouter: require("./MappingPassCapabilityRouter"),
    MopDockCleanManualTriggerCapabilityRouter: require("./MopDockCleanManualTriggerCapabilityRouter"),
    MopDockDryManualTriggerCapabilityRouter: require("./MopDockDryManualTriggerCapabilityRouter"),
    MopDockMopWashTemperatureControlCapabilityRouter : require("./MopDockMopWashTemperatureControlCapabilityRouter"),
    ObstacleImagesCapabilityRouter: require("./ObstacleImagesCapabilityRouter"),
    PendingMapChangeHandlingCapabilityRouter: require("./PendingMapChangeHandlingCapabilityRouter"),
    PresetSelectionCapabilityRouter: require("./PresetSelectionCapabilityRouter"),
    QuirksCapabilityRouter: require("./QuirksCapabilityRouter"),
    SimpleToggleCapabilityRouter: require("./SimpleToggleCapabilityRouter"),
    SpeakerTestCapabilityRouter: require("./SpeakerTestCapabilityRouter"),
    SpeakerVolumeControlCapabilityRouter: require("./SpeakerVolumeControlCapabilityRouter"),
    StatisticsCapabilityRouter: require("./StatisticsCapabilityRouter"),
    VoicePackManagementCapabilityRouter: require("./VoicePackManagementCapabilityRouter"),
    WifiConfigurationCapabilityRouter: require("./WifiConfigurationCapabilityRouter"),
    WifiScanCapabilityRouter: require("./WifiScanCapabilityRouter"),
    ZoneCleaningCapabilityRouter: require("./ZoneCleaningCapabilityRouter"),
};
