module.exports = {
    AutoEmptyDockManualTriggerCapabilityRouter: require("./AutoEmptyDockManualTriggerCapabilityRouter"),
    BasicControlCapabilityRouter: require("./BasicControlCapabilityRouter"),
    CombinedVirtualRestrictionsCapabilityRouter: require("./CombinedVirtualRestrictionsCapabilityRouter"),
    ConsumableMonitoringCapabilityRouter: require("./ConsumableMonitoringCapabilityRouter"),
    DebugCapabilityRouter: require("./DebugCapabilityRouter"),
    DoNotDisturbCapabilityRouter: require("./DoNotDisturbCapabilityRouter"),
    GoToLocationCapabilityRouter: require("./GoToLocationCapabilityRouter"),
    LocateCapabilityRouter: require("./LocateCapabilityRouter"),
    ManualControlCapabilityRouter: require("./ManualControlCapabilityRouter"),
    MapResetCapabilityRouter: require("./MapResetCapabilityRouter"),
    MapSegmentEditCapabilityRouter: require("./MapSegmentEditCapabilityRouter"),
    MapSegmentRenameCapabilityRouter: require("./MapSegmentRenameCapabilityRouter"),
    MapSegmentationCapabilityRouter: require("./MapSegmentationCapabilityRouter"),
    MapSnapshotCapabilityRouter: require("./MapSnapshotCapabilityRouter"),
    MappingPassCapabilityRouter: require("./MappingPassCapabilityRouter"),
    PendingMapChangeHandlingCapabilityRouter: require("./PendingMapChangeHandlingCapabilityRouter"),
    PresetSelectionCapabilityRouter: require("./PresetSelectionCapabilityRouter"),
    SensorCalibrationCapabilityRouter: require("./SensorCalibrationCapabilityRouter"),
    SimpleToggleCapabilityRouter: require("./SimpleToggleCapabilityRouter"),
    SpeakerTestCapabilityRouter: require("./SpeakerTestCapabilityRouter"),
    SpeakerVolumeControlCapabilityRouter: require("./SpeakerVolumeControlCapabilityRouter"),
    StatisticsCapabilityRouter: require("./StatisticsCapabilityRouter"),
    VoicePackManagementCapabilityRouter: require("./VoicePackManagementCapabilityRouter"),
    WifiConfigurationCapabilityRouter: require("./WifiConfigurationCapabilityRouter"),
    ZoneCleaningCapabilityRouter: require("./ZoneCleaningCapabilityRouter")
};
