module.exports = {
    BasicControlCapabilityRouter: require("./BasicControlCapabilityRouter"),
    IntensityPresetCapabilityRouter: require("./IntensityPresetCapabilityRouter"),
    LEDControlCapabilityRouter: require("./LEDControlCapabilityRouter"),
    ConsumableMonitoringCapabilityRouter: require("./ConsumableMonitoringCapabilityRouter"),
    ZoneCleaningCapabilityRouter: require("./ZoneCleaningCapabilityRouter"),
    GoToLocationCapabilityRouter: require("./GoToLocationCapabilityRouter"),
    WifiConfigurationCapabilityRouter: require("./WifiConfigurationCapabilityRouter"),
    MapSnapshotCapabilityRouter: require("./MapSnapshotCapabilityRouter"),
    LocateCapabilityRouter: require("./LocateCapabilityRouter"),
    ManualControlCapabilityRouter: require("./ManualControlCapabilityRouter"),
    CombinedVirtualRestrictionsCapabilityRouter: require("./CombinedVirtualRestrictionsCapabilityRouter"),
    PersistentMapControlCapabilityRouter: require("./PersistentMapControlCapabilityRouter"),
    SensorCalibrationCapabilityRouter: require("./SensorCalibrationCapabilityRouter"),
    SpeakerVolumeControlCapabilityRouter: require("./SpeakerVolumeControlCapabilityRouter"),
    RawCommandCapabilityRouter: require("./RawCommandCapabilityRouter"),
    MapSegmentationCapabilityRouter: require("./MapSegmentationCapabilityRouter"),
    DoNotDisturbCapabilityRouter: require("./DoNotDisturbCapabilityRouter"),
    CarpetModeControlCapabilityRouter: require("./CarpetModeControlCapabilityRouter"),
    SpeakerTestCapabilityRouter: require("./SpeakerTestCapabilityRouter")
};
