module.exports = {
    Dreame1CBasicControlCapability: require("./Dreame1CBasicControlCapability"),
    Dreame1CZoneCleaningCapability: require("./Dreame1CZoneCleaningCapability"),
    DreameBasicControlCapability: require("./DreameBasicControlCapability"),
    DreameCarpetModeControlCapability: require("./DreameCarpetModeControlCapability"),
    DreameCombinedVirtualRestrictionsCapability: require("./DreameCombinedVirtualRestrictionsCapability"),
    DreameConsumableMonitoringCapability: require("./DreameConsumableMonitoringCapability"),
    DreameFanSpeedControlCapability: require("./DreameFanSpeedControlCapability"),
    DreameLocateCapability: require("./DreameLocateCapability"),
    DreameMapResetCapability: require("./DreameMapResetCapability"),
    DreameMapSegmentEditCapability: require("./DreameMapSegmentEditCapability"),
    DreameMapSegmentRenameCapability: require("./DreameMapSegmentRenameCapability"),
    DreameMapSegmentationCapability: require("./DreameMapSegmentationCapability"),
    DreamePersistentMapControlCapability: require("./DreamePersistentMapControlCapability"),
    DreameSpeakerTestCapability: require("./DreameSpeakerTestCapability"),
    DreameSpeakerVolumeControlCapability: require("./DreameSpeakerVolumeControlCapability"),
    DreameVoicePackManagementCapability: require("./DreameVoicePackManagementCapability"),
    DreameWaterUsageControlCapability: require("./DreameWaterUsageControlCapability"),
    DreameWifiConfigurationCapability: require("./DreameWifiConfigurationCapability"),
    DreameZoneCleaningCapability: require("./DreameZoneCleaningCapability")
};
