module.exports = {
    BasicControlCapability: require("./BasicControlCapability"),
    IntensityPresetCapability: require("./IntensityPresetCapability"),
    FanSpeedControlCapability: require("./FanSpeedControlCapability"),
    WaterUsageControlCapability: require("./WaterUsageControlCapability"),
    CarpetTurboControlCapability: require("./CarpetTurboControlCapability"),
    ConsumableMonitoringCapability: require("./ConsumableMonitoringCapability"),
    ZoneCleaningCapability: require("./ZoneCleaningCapability"),
    GoToLocationCapability: require("./GoToLocationCapability"),
    WifiConfigurationCapability: require("./WifiConfigurationCapability"),
    MapSnapshotCapability: require("./MapSnapshotCapability"),
    LocateCapability: require("./LocateCapability"),
    CombinedVirtualRestrictionsCapability: require("./CombinedVirtualRestrictionsCapability"),
    PersistentMapControlCapability: require("./PersistentMapControlCapability"),
    MapSegmentationCapability: require("./MapSegmentationCapability"),
    RawCommandCapability: require("./RawCommandCapability"),
};