name: Bug Report
description: Please only open a bug report when you're sure that it is in fact a bug in Valetudo
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Hey,
        
        before you open a bug report, please take a moment and revisit the problem at hand.
        Ask yourself: "Is this really a bug, or am I just looking for help?"
        
        From a user perspective, these two things may look like they're the same thing; they are quite different though.
        Bugs are:
        
        1. Genuinely and indisputably erroneous
        2. Reproducible
        3. Clearly caused/controlled by Valetudo and **not** the vendor firmware
        
        If something just doesn't behave like you'd expect it to, that is a support request.
        
        Additionally, do **not** open bug reports for Home Assistant deprecation warnings, unless the thing they report breaks _very soon_. Not all deprecation warnings will be fixed instantly in Valetudo, as otherwise, updating Valetudo would force people to also update Home Assistant.
        
  - type: textarea
    id: what-is-happening
    attributes:
      label: What is happening?
      description: What behavior do you observe?
    validations:
      required: true



  - type: textarea
    id: what-should-be-happening
    attributes:
      label: What should be happening?
      description: |
        What would be the correct behavior?
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: valetudo-version
    attributes:
      label: Please enter the Valetudo version you're using
    validations:
      required: true

  - type: input
    id: robot
    attributes:
      label: Please enter the vendor and model of robot you're using
    validations:
      required: true

  - type: input
    id: robot-firmware
    attributes:
      label: Please enter the robot's firmware version you're using
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Anything else relevant to the situation.<br/>
        Think: Browser, Phone, Home Assistant version, Wi-Fi access points, Etc.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots here

