module.exports = {
    ViomiBasicControlCapability: require("./ViomiBasicControlCapability"),
    ViomiFanSpeedControlCapability: require("./ViomiFanSpeedControlCapability"),
    ViomiWaterUsageControlCapability: require("./ViomiWaterUsageControlCapability"),
    ViomiWifiConfigurationCapability: require("./ViomiWifiConfigurationCapability"),
    ViomiRawCommandCapability: require("./ViomiRawCommandCapability"),
    ViomiLocateCapability: require("./ViomiLocateCapability"),
    ViomiConsumableMonitoringCapability: require("./ViomiConsumableMonitoringCapability"),
    ViomiZoneCleaningCapability: require("./ViomiZoneCleaningCapability"),
    ViomiPersistentMapControlCapability: require("./ViomiPersistentMapControlCapability"),
    ViomiCombinedVirtualRestrictionsCapability: require("./ViomiCombinedVirtualRestrictionsCapability"),
    ViomiSpeakerTestCapability: require("./ViomiSpeakerTestCapability"),
    ViomiSpeakerVolumeControlCapability: require("./ViomiSpeakerVolumeControlCapability"),
    ViomiCarpetModeControlCapability: require("./ViomiCarpetModeControlCapability"),
    ViomiSensorCalibrationCapability: require("./ViomiSensorCalibrationCapability"),
    ViomiManualControlCapability: require("./ViomiManualControlCapability"),
};
