module.exports = {
    ViomiBasicControlCapability: require("./ViomiBasicControlCapability"),
    ViomiCarpetModeControlCapability: require("./ViomiCarpetModeControlCapability"),
    ViomiCombinedVirtualRestrictionsCapability: require("./ViomiCombinedVirtualRestrictionsCapability"),
    ViomiConsumableMonitoringCapability: require("./ViomiConsumableMonitoringCapability"),
    ViomiFanSpeedControlCapability: require("./ViomiFanSpeedControlCapability"),
    ViomiLocateCapability: require("./ViomiLocateCapability"),
    ViomiManualControlCapability: require("./ViomiManualControlCapability"),
    ViomiMapResetCapability: require("./ViomiMapResetCapability"),
    ViomiMapSegmentEditCapability: require("./ViomiMapSegmentEditCapability"),
    ViomiMapSegmentRenameCapability: require("./ViomiMapSegmentRenameCapability"),
    ViomiMapSegmentationCapability: require("./ViomiMapSegmentationCapability"),
    ViomiPersistentMapControlCapability: require("./ViomiPersistentMapControlCapability"),
    ViomiRawCommandCapability: require("./ViomiRawCommandCapability"),
    ViomiSpeakerTestCapability: require("./ViomiSpeakerTestCapability"),
    ViomiSpeakerVolumeControlCapability: require("./ViomiSpeakerVolumeControlCapability"),
    ViomiVoicePackManagementCapability: require("./ViomiVoicePackManagementCapability"),
    ViomiWaterUsageControlCapability: require("./ViomiWaterUsageControlCapability"),
    ViomiWifiConfigurationCapability: require("./ViomiWifiConfigurationCapability"),
    ViomiZoneCleaningCapability: require("./ViomiZoneCleaningCapability"),
};
