module.exports = {
    RoborockBasicControlCapability: require("./RoborockBasicControlCapability"),
    RoborockCarpetModeControlCapability: require("./RoborockCarpetModeControlCapability"),
    RoborockCombinedVirtualRestrictionsCapability: require("./RoborockCombinedVirtualRestrictionsCapability"),
    RoborockConsumableMonitoringCapability: require("./RoborockConsumableMonitoringCapability"),
    RoborockCurrentStatisticsCapability: require("./RoborockCurrentStatisticsCapability"),
    RoborockDoNotDisturbCapability: require("./RoborockDoNotDisturbCapability"),
    RoborockFanSpeedControlCapability: require("./RoborockFanSpeedControlCapability"),
    RoborockGoToLocationCapability: require("./RoborockGoToLocationCapability"),
    RoborockLocateCapability: require("./RoborockLocateCapability"),
    RoborockManualControlCapability: require("./RoborockManualControlCapability"),
    RoborockMapResetCapability: require("./RoborockMapResetCapability"),
    RoborockMapSegmentEditCapability: require("./RoborockMapSegmentEditCapability"),
    RoborockMapSegmentRenameCapability: require("./RoborockMapSegmentRenameCapability"),
    RoborockMapSegmentationCapability: require("./RoborockMapSegmentationCapability"),
    RoborockMapSnapshotCapability: require("./RoborockMapSnapshotCapability"),
    RoborockMultiMapMapResetCapability: require("./RoborockMultiMapMapResetCapability"),
    RoborockMultiMapPersistentMapControlCapability: require("./RoborockMultiMapPersistentMapControlCapability"),
    RoborockPersistentMapControlCapability: require("./RoborockPersistentMapControlCapability"),
    RoborockSpeakerTestCapability: require("./RoborockSpeakerTestCapability"),
    RoborockSpeakerVolumeControlCapability: require("./RoborockSpeakerVolumeControlCapability"),
    RoborockStatusLEDControlCapability: require("./RoborockStatusLEDControlCapability"),
    RoborockTotalStatisticsCapability: require("./RoborockTotalStatisticsCapability"),
    RoborockVoicePackManagementCapability: require("./RoborockVoicePackManagementCapability"),
    RoborockWaterUsageControlCapability: require("./RoborockWaterUsageControlCapability"),
    RoborockWifiConfigurationCapability: require("./RoborockWifiConfigurationCapability"),
    RoborockZoneCleaningCapability: require("./RoborockZoneCleaningCapability")
};
