#!/bin/bash -e

####################################################################################
#
# This file provides a simple way to run a development version of valetudo on your
# local computer. It should be invoked from the main directory as ./develop/run.sh
#
# Environment settings and configuration are read from the directory develop/local/.
# If that directory doesn't exist, it will be created on the first invocation of
# the script.
#
# For more information, see the file HOWTO.md in this directory.
#
####################################################################################


# check if we're in the right (main) directory
if [ "$0" != "./develop/run" ]; then
    echo "Please run this script from the main Valetudo directory, i.e. as ./develop/run"
    exit 1
fi

# check if necessary files exist
if [ ! -f "./develop/config.json.example" ]; then
    echo "Example configuration not found, bailing out"
    exit 1
fi

if [ ! -f "./develop/env.example" ]; then
    echo "Example environment not found, bailing out"
    exit 1
fi

if [ ! -f "./develop/device.conf.example" ]; then
    echo "Example device.conf not found, bailing out"
    exit 1
fi

# check if local configuration exists, else create
if [ ! -d "./develop/local" ]; then
    echo "Local configuration not found, initializing ..."
    echo ""

    mkdir ./develop/local
    cp ./develop/config.json.example ./develop/local/config.json
    cp ./develop/device.conf.example ./develop/local/device.conf
    cp ./develop/device.token.example ./develop/local/device.token

    echo "# This file contains environment settings for your local valetudo development." > ./develop/local/env
    echo "# Edit it according to your individual setup." >> ./develop/local/env
    echo "" >> ./develop/local/env

    tail -n +3 ./develop/env.example >> ./develop/local/env

    echo "Local configuration created. Please edit the files in ./develop/local/"
    echo "to suit your needs, then start this script again."
    echo ""

    echo "Initializing local (development) maps and paths ..."
    # Create empty map files for initial run, to prevent errors.
    # This should be revisited when the map testing logic is adapted.
    if [ ! -f "./map" ]; then
        echo "Creating empty map file"
        touch ./map
    fi

    if [ ! -f "./log" ]; then
        echo "Creating empty path log file"
        touch ./log
    fi

    exit 1
fi

if [ ! -f "./develop/local/device.conf" ]; then
    echo "./develop/local/device.conf doesn't exist. Please copy it from the robot. See develop/HOWTO.md."
    exit 1
fi

if [ ! -f "./develop/local/device.token" ]; then
    echo "./develop/local/device.token doesn't exist. Please copy it from the robot. See develop/HOWTO.md."
    exit 1
fi

if [ ! -f "./develop/local/env" ]; then
    echo "Environment settings not found, bailing out"
    exit 1
fi

# default command to run
VALETUDO_NODE_JS=nodejs

# load environment
. ./develop/local/env

echo "Starting Valetudo locally with the following settings:"
echo ""
grep -v '#' ./develop/local/env | grep '=' | cat
cat ./develop/local/device.conf
echo ""

$VALETUDO_NODE_JS ./index.js

