module.exports = {
    "Dreame1CValetudoRobot": require("./Dreame1CValetudoRobot"),
    "Dreame1TValetudoRobot": require("./Dreame1TValetudoRobot"),
    "DreameD10SPlusValetudoRobot": require("./DreameD10SPlusValetudoRobot"),
    "DreameD10SProValetudoRobot": require("./DreameD10SProValetudoRobot"),
    "DreameD9ProPlusValetudoRobot": require("./DreameD9ProPlusValetudoRobot"),
    "DreameD9ProValetudoRobot": require("./DreameD9ProValetudoRobot"),
    "DreameD9ValetudoRobot": require("./DreameD9ValetudoRobot"),
    "DreameF9ValetudoRobot": require("./DreameF9ValetudoRobot"),
    "DreameL10ProValetudoRobot": require("./DreameL10ProValetudoRobot"),
    "DreameL10SProValetudoRobot": require("./DreameL10SProValetudoRobot"),
    "DreameL10SUltraValetudoRobot": require("./DreameL10SUltraValetudoRobot"),
    "DreameL10UltraValetudoRobot": require("./DreameL10UltraValetudoRobot"),
    "DreameMovaZ500ValetudoRobot": require("./DreameMovaZ500ValetudoRobot"),
    "DreameP2148ValetudoRobot": require("./DreameP2148ValetudoRobot"),
    "DreameP2149ValetudoRobot": require("./DreameP2149ValetudoRobot"),
    "DreameP2150ValetudoRobot": require("./DreameP2150ValetudoRobot"),
    "DreameW10ValetudoRobot": require("./DreameW10ValetudoRobot"),
    "DreameX10PlusValetudoRobot": require("./DreameX10PlusValetudoRobot"),
    "DreameZ10ProValetudoRobot": require("./DreameZ10ProValetudoRobot")
};
