module.exports = {
    CecotecBasicControlCapability: require("./CecotecBasicControlCapability"),
    CecotecCarpetModeControlCapability: require("./CecotecCarpetModeControlCapability"),
    CecotecCombinedVirtualRestrictionsCapability: require("./CecotecCombinedVirtualRestrictionsCapability"),
    CecotecConsumableMonitoringCapability: require("./CecotecConsumableMonitoringCapability"),
    CecotecDebugCapability: require("./CecotecDebugCapability"),
    CecotecDoNotDisturbCapability: require("./CecotecDoNotDisturbCapability"),
    CecotecFanSpeedControlCapability: require("./CecotecFanSpeedControlCapability"),
    CecotecGoToLocationCapability: require("./CecotecGoToLocationCapability"),
    CecotecLocateCapability: require("./CecotecLocateCapability"),
    CecotecManualControlCapability: require("./CecotecManualControlCapability"),
    CecotecMapResetCapability: require("./CecotecMapResetCapability"),
    CecotecMapSegmentEditCapability: require("./CecotecMapSegmentEditCapability"),
    CecotecMapSegmentRenameCapability: require("./CecotecMapSegmentRenameCapability"),
    CecotecMapSegmentationCapability: require("./CecotecMapSegmentationCapability"),
    CecotecPendingMapChangeHandlingCapability: require("./CecotecPendingMapChangeHandlingCapability"),
    CecotecPersistentMapControlCapability: require("./CecotecPersistentMapControlCapability"),
    CecotecSpeakerTestCapability: require("./CecotecSpeakerTestCapability"),
    CecotecSpeakerVolumeControlCapability: require("./CecotecSpeakerVolumeControlCapability"),
    CecotecWaterUsageControlCapability: require("./CecotecWaterUsageControlCapability"),
    CecotecWifiConfigurationCapability: require("./CecotecWifiConfigurationCapability"),
    CecotecZoneCleaningCapability: require("./CecotecZoneCleaningCapability"),
};
