module.exports = {
    ViomiBasicControlCapability: require("./ViomiBasicControlCapability"),
    ViomiCarpetModeControlCapability: require("./ViomiCarpetModeControlCapability"),
    ViomiCleanRouteControlCapability: require("./ViomiCleanRouteControlCapability"),
    ViomiCombinedVirtualRestrictionsCapability: require("./ViomiCombinedVirtualRestrictionsCapability"),
    ViomiConsumableMonitoringCapability: require("./ViomiConsumableMonitoringCapability"),
    ViomiCurrentStatisticsCapability: require("./ViomiCurrentStatisticsCapability"),
    ViomiDoNotDisturbCapability: require("./ViomiDoNotDisturbCapability"),
    ViomiFanSpeedControlCapability: require("./ViomiFanSpeedControlCapability"),
    ViomiLocateCapability: require("./ViomiLocateCapability"),
    ViomiManualControlCapability: require("./ViomiManualControlCapability"),
    ViomiMapResetCapability: require("./ViomiMapResetCapability"),
    ViomiMapSegmentEditCapability: require("./ViomiMapSegmentEditCapability"),
    ViomiMapSegmentRenameCapability: require("./ViomiMapSegmentRenameCapability"),
    ViomiMapSegmentationCapability: require("./ViomiMapSegmentationCapability"),
    ViomiOperationModeControlCapability: require("./ViomiOperationModeControlCapability"),
    ViomiPersistentMapControlCapability: require("./ViomiPersistentMapControlCapability"),
    ViomiSpeakerTestCapability: require("./ViomiSpeakerTestCapability"),
    ViomiSpeakerVolumeControlCapability: require("./ViomiSpeakerVolumeControlCapability"),
    ViomiVoicePackManagementCapability: require("./ViomiVoicePackManagementCapability"),
    ViomiWaterUsageControlCapability: require("./ViomiWaterUsageControlCapability"),
    ViomiZoneCleaningCapability: require("./ViomiZoneCleaningCapability"),
};
